const reI = "\\s*([+-]?\\d+)\\s*",
  reN = "\\s*([+-]?(?:\\d*\\.)?\\d+(?:[eE][+-]?\\d+)?)\\s*",
  reP = "\\s*([+-]?(?:\\d*\\.)?\\d+(?:[eE][+-]?\\d+)?)%\\s*";
const reTokenStart = "(?:\\s*[\"'`:\\s]\\s*)";
const reTokenEnd = "(?:\\s*[\"'`;\\s]\\s*)";

const Colors = {
  reHex: '#[0-9a-f]{3,8}',
  reRgbInteger: `rgb\\(${reI},${reI},${reI}\\)`,
  reRgbPercent: `rgb\\(${reP},${reP},${reP}\\)`,
  reRgbaInteger: `rgba\\(${reI},${reI},${reI},${reN}\\)`,
  reRgbaPercent: `rgba\\(${reP},${reP},${reP},${reN}\\)`,
  reHslPercent: `hsl\\(${reN},${reP},${reP}\\)`,
  reHslaPercent: `hsla\\(${reN},${reP},${reP},${reN}\\)`,
};

const WEB_COLORS = [
    "transparent",
    "aquamarine",
    "azure",
    "beige",
    "bisque",
    "black",
    "blanchedalmond",
    "blue",
    "blueviolet",
    "brown",
    "burlywood",
    "cadetblue",
    "chartreuse",
    "chocolate",
    "coral",
    "cornflowerblue",
    "cornsilk",
    "crimson",
    "cyan",
    "darkblue",
    "darkcyan",
    "darkgoldenrod",
    "darkgray",
    "darkgreen",
    "darkgrey",
    "darkkhaki",
    "darkmagenta",
    "darkolivegreen",
    "darkorange",
    "darkorchid",
    "darkred",
    "darksalmon",
    "darkseagreen",
    "darkslateblue",
    "darkslategray",
    "darkslategrey",
    "darkturquoise",
    "darkviolet",
    "deeppink",
    "deepskyblue",
    "dimgray",
    "dimgrey",
    "dodgerblue",
    "firebrick",
    "floralwhite",
    "forestgreen",
    "fuchsia",
    "gainsboro",
    "ghostwhite",
    "gold",
    "goldenrod",
    "gray",
    "green",
    "greenyellow",
    "grey",
    "honeydew",
    "hotpink",
    "indianred",
    "indigo",
    "ivory",
    "khaki",
    "lavender",
    "lavenderblush",
    "lawngreen",
    "lemonchiffon",
    "lightblue",
    "lightcoral",
    "lightcyan",
    "lightgoldenrodyellow",
    "lightgray",
    "lightgreen",
    "lightgrey",
    "lightpink",
    "lightsalmon",
    "lightseagreen",
    "lightskyblue",
    "lightslategray",
    "lightslategrey",
    "lightsteelblue",
    "lightyellow",
    "lime",
    "limegreen",
    "linen",
    "magenta",
    "maroon",
    "mediumaquamarine",
    "mediumblue",
    "mediumorchid",
    "mediumpurple",
    "mediumseagreen",
    "mediumslateblue",
    "mediumspringgreen",
    "mediumturquoise",
    "mediumvioletred",
    "midnightblue",
    "mintcream",
    "mistyrose",
    "moccasin",
    "navajowhite",
    "navy",
    "oldlace",
    "olive",
    "olivedrab",
    "orange",
    "orangered",
    "orchid",
    "palegoldenrod",
    "palegreen",
    "paleturquoise",
    "palevioletred",
    "papayawhip",
    "peachpuff",
    "peru",
    "pink",
    "plum",
    "powderblue",
    "purple",
    "rebeccapurple",
    "red",
    "rosybrown",
    "royalblue",
    "saddlebrown",
    "salmon",
    "sandybrown",
    "seagreen",
    "seashell",
    "sienna",
    "silver",
    "skyblue",
    "slateblue",
    "slategray",
    "slategrey",
    "snow",
    "springgreen",
    "steelblue",
    "tan",
    "teal",
    "thistle",
    "tomato",
    "turquoise",
    "violet",
    "wheat",
    "white",
    "whitesmoke",
    "yellow",
    "yellowgreen",
];


const Matcher = `${reTokenStart}(?<color>${[...Object.values(Colors), ...WEB_COLORS].join('|')})${reTokenEnd}`

const testString = 'box-sizing: Blue; height: 100px; width: 100px; background-color: red; color: white; border: 1px solid black; padding: 10px; margin: 10px; display: flex; justify-content: center; align-items: center;border-color: rgba(0, 0, 0, 0.5);outline:#555;';

const regex =  new RegExp(Matcher, "gi")

let color;

while ((color = regex.exec(testString)?.groups.color)) {
    console.log(`Found "${color}". Next starts at ${regex.lastIndex}.`);
}